### PR TITLE
Feature/theme switcher

### LINKED ISSUE #29: Toggle Dark/Light mode option
Enable dark/light mode on the UI

### PR DESCRIPTION
**Pull request by standrd**
Please let me know what you think and if I need to update something. If bounty on #29 applies, here is the receiver address: 0xD7239035d3C0819b380b8d1c8Adf5Db7682FcCAd

### CODE REVIEW

**Comment by TheNewAutonomy** [comment]
Please can you confirm the network that you want paying to 0xD7239035d3C0819b380b8d1c8Adf5Db7682FcCAd  on? Is it xDai, Celo or Ethereum main network?

**Comment by standrd** [comment]
> Please can you confirm the network that you want paying to 0xD7239035d3C0819b380b8d1c8Adf5Db7682FcCAd on? Is it xDai, Celo or Ethereum main network?

Celo would be great, thank you! Address confirmed.

**Comment by TheNewAutonomy** [comment]
This bounty has been paid https://explorer.celo.org/tx/0xcc12d8ad0c9f191dcc9ffdcbbcf1d9ee35d1b1497ee4f24654519700b88d641b/token-transfers

**Comment by TheNewAutonomy** [comment]
Since this was paid on Celo from the Symmetric wallet, a matching transaction exists taking the same amount of SYMM out of the xDai community wallet to ensure the payment ultimately comes from the community wallet. https://blockscout.com/poa/xdai/tx/0x3cf762270d8e20e3c2622cd4da39a2e3b21639029d1fd528235ec4c770897d16

**Pull request merged**
