### PR TITLE
Kp dev

### PR DESCRIPTION
**Pull request by smart-tech-master**
I've fixed issue 64

### CODE REVIEW

**Comment by tqmvt** [comment]
@prestonkevin can we use appropriate social icons?

image

All icons don't match for each title

**Comment by tqmvt** [comment]
@prestonkevin And let's remove telegram as we use discord instead

**Comment by smart-tech-master** [comment]
> @prestonkevin And let's remove telegram as we use discord instead

Screenshot_75
Screenshot_76
How about this?

**Comment by tqmvt** [comment]
@prestonkevin looks good to me

**Review by tqmvt — APPROVED** [review]

**Comment by tqmvt** [comment]
closes #64

**Pull request merged**
